# Generated by Django 4.2.4 on 2023-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender sending an email', max_length=1000, verbose_name='Name of Sender:')),
                ('message', models.TextField(help_text='Message received', verbose_name='Content Message:')),
            ],
            options={
                'verbose_name': 'My Contact Message',
                'verbose_name_plural': 'My Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title i occupy', max_length=100, verbose_name='Title')),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The technology i use', max_length=100, verbose_name='Name')),
                ('color', models.CharField(help_text='The color i choose', max_length=100, verbose_name='Color')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The technology i use', max_length=100, verbose_name='Name')),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='My experience', max_length=100, verbose_name='Title')),
                ('icon', models.ImageField(upload_to='')),
                ('iconBg', models.CharField(help_text='icon color', max_length=100, verbose_name='icon color')),
                ('company_name', models.CharField(help_text='Company experience', max_length=100, verbose_name='Company')),
                ('date', models.CharField(help_text=' experience date', max_length=100, verbose_name='Date')),
                ('points', models.ManyToManyField(to='react_portfolio_app.points')),
            ],
        ),
    ]
