# Generated by Django 4.2.4 on 2023-09-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project', max_length=100, verbose_name='Name')),
                ('description', models.TextField(help_text='The description', verbose_name='Description')),
                ('image', models.ImageField(upload_to='')),
                ('source_code_link', models.URLField()),
                ('tags', models.ManyToManyField(to='react_portfolio_app.tags')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
