# Generated by Django 4.2.4 on 2023-09-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_portfolio_app', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField(help_text='The testimonial')),
                ('name', models.CharField(help_text='Name of the individual', max_length=200)),
                ('designation', models.CharField(help_text='office of the individual', max_length=200)),
                ('company', models.CharField(help_text='company of the individual', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technology'},
        ),
    ]
